name: Daily Website Update Windows

on:
  schedule:
    #- cron: '*/5 * * * *'     # Testing: Every 5 min
    #- cron: '44 5 * * *'  # 11:35 PM CST (5:35 AM UTC)
  workflow_dispatch:

permissions:
  contents: write   # <-- required for git push

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run first PowerShell script
        shell: powershell
        run: ./format_gameNumber.ps1

      - name: Run second PowerShell script
        shell: powershell
        run: ./001.ps1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_site.py

      - name: Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Daily update" || echo "No changes to commit"
          git push -f https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
